//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MpTradingSytemMVC2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Prezzi
    {
        [Key]
        public long IdPrezzo { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Apertura { get; set; }
        public decimal Chiusura { get; set; }
        public decimal Massimo { get; set; }
        public decimal Minimo { get; set; }
        public decimal Volume { get; set; }
        public string SimboloTitolo { get; set; }
        public Nullable<long> IdTitolo { get; set; }
        public string Segnalazioni { get; set; }
    
        public virtual Titoli Titoli { get; set; }

        public List<dynamic> DatiPrezzi { get; set; }
        public List<System.Web.Helpers.WebGridColumn> ColsPrezzi { get; set; }
        public int totalRowsPrezzi { get; set; }
    }
}
